# Generated by Django 5.2.3 on 2026-01-31 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email Address')),
                ('mobile', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Mobile Number')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('mobile_verified', models.BooleanField(default=False, verbose_name='Mobile Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('firebase_uid', models.CharField(blank=True, db_index=True, help_text='Firebase Authentication UID for Firebase-based login', max_length=128, null=True, unique=True, verbose_name='Firebase UID')),
                ('auth_provider', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone (Firebase)'), ('google', 'Google (Firebase)')], default='email', max_length=20, verbose_name='Authentication Provider')),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google ID')),
                ('firestore_doc_id', models.CharField(blank=True, help_text='Reference to Firebase Firestore document', max_length=255, null=True, verbose_name='Firestore Document ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_customuser',
            },
        ),
        migrations.CreateModel(
            name='FirebaseUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firebase_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firebase User Profile',
                'verbose_name_plural': 'Firebase User Profiles',
                'db_table': 'accounts_firebase_user_profile',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('otp_type', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset')], max_length=20, verbose_name='OTP Type')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'accounts_otp',
            },
        ),
    ]
