# Generated by Django 5.2.3 on 2026-01-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='resume',
            field=models.FileField(blank=True, help_text="User's resume file (PDF/DOC)", null=True, upload_to='resumes/', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser'), ('ADMIN', 'Admin'), ('USER', 'User')], default='USER', help_text='User role for access control', max_length=10, verbose_name='User Role'),
        ),
    ]
