# Generated by Django 5.2.3 on 2026-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_resume_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio URL'),
        ),
    ]
