# Generated by Django 5.2.3 on 2026-01-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_linkedin_url_customuser_portfolio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
    ]
