# Generated by Django 6.0.1 on 2026-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification')], max_length=20, verbose_name='OTP Type'),
        ),
    ]
