# Generated by Django 6.0.1 on 2026-02-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_otp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Position'),
        ),
    ]
