# Generated by Django 6.0.1 on 2026-03-02 04:00

from django.db import migrations

def activate_existing_users(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(is_active=False).update(is_active=True)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_current_position'),
    ]

    operations = [
        migrations.RunPython(activate_existing_users),
    ]
