# Generated by Django 6.0.1 on 2026-04-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_activate_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_version',
            field=models.IntegerField(default=0, help_text='Incremented on login to invalidate previous tokens', verbose_name='Token Version'),
        ),
    ]
