# Generated by Django 6.0.1 on 2026-04-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Brief summary shown on the card', verbose_name='Short Description')),
                ('content', models.TextField(blank=True, help_text='Detailed news content', verbose_name='Full Content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Cover Image')),
                ('link_url', models.URLField(blank=True, help_text='Link to full article or external site', null=True, verbose_name='External Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News & Update',
                'verbose_name_plural': 'News & Updates',
                'db_table': 'content_newsitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1000, verbose_name='Total Visitors')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Counter',
                'verbose_name_plural': 'Visitor Counter',
                'db_table': 'content_visitorcount',
            },
        ),
    ]
