# Generated by Django 5.2.3 on 2026-01-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('hr_name', models.CharField(max_length=255, verbose_name='HR Name')),
                ('hr_email', models.EmailField(max_length=254, verbose_name='HR Email')),
                ('hr_phone', models.CharField(max_length=15, verbose_name='HR Phone')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('hiring_for', models.CharField(blank=True, help_text='Positions or roles to hire for', max_length=255, verbose_name='Hiring For')),
                ('no_of_positions', models.PositiveIntegerField(default=1, verbose_name='Number of Positions')),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp')], default='email', max_length=20, verbose_name='Preferred Contact Method')),
                ('estimated_start_date', models.DateField(blank=True, null=True, verbose_name='Estimated Start Date')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='enquiries/%Y/%m/', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Corporate Enquiry',
                'verbose_name_plural': 'Corporate Enquiries',
                'db_table': 'enquiries_corporateenquiry',
                'ordering': ['-created_at'],
            },
        ),
    ]
