# Generated by Django 6.0.1 on 2026-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateenquiry',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=20, verbose_name='Preferred Contact Method'),
        ),
    ]
