# Generated by Django 5.2.3 on 2026-01-31 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('part_time', 'Part-time')], default='full_time', max_length=20, verbose_name='Job Type')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('skills_required', models.TextField(help_text='Comma-separated list of skills', verbose_name='Skills Required')),
                ('salary_range', models.CharField(blank=True, max_length=100, verbose_name='Salary Range')),
                ('experience_required', models.CharField(blank=True, help_text='e.g., 2-3 years', max_length=100, verbose_name='Experience Required')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Status')),
                ('apply_deadline', models.DateTimeField(verbose_name='Apply Deadline')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Job')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Vacancy',
                'verbose_name_plural': 'Job Vacancies',
                'db_table': 'jobs_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('resume', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='Resume/CV')),
                ('resume_file_name', models.CharField(blank=True, max_length=255, verbose_name='Resume File Name')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio URL')),
                ('expected_salary', models.CharField(blank=True, max_length=100, verbose_name='Expected Salary')),
                ('notice_period', models.CharField(blank=True, max_length=100, verbose_name='Notice Period')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20, verbose_name='Status')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Cover Letter')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'db_table': 'jobs_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Question')),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('email', 'Email')], default='text', max_length=20, verbose_name='Field Type')),
                ('field_name', models.CharField(help_text='Technical name for the field (snake_case)', max_length=100, verbose_name='Field Name')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('options', models.TextField(blank=True, help_text='For dropdown fields, comma-separated options', verbose_name='Options')),
                ('help_text', models.CharField(blank=True, help_text='Placeholder or helper text', max_length=255, verbose_name='Help Text')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display the field', verbose_name='Display Order')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Requirement',
                'verbose_name_plural': 'Job Requirements',
                'db_table': 'jobs_requirement',
                'ordering': ['job', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.TextField(verbose_name='Response')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobs.jobapplication')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='jobs.jobrequirement')),
            ],
            options={
                'verbose_name': 'Application Response',
                'verbose_name_plural': 'Application Responses',
                'db_table': 'jobs_application_response',
            },
        ),
    ]
