# Generated by Django 6.0.1 on 2026-02-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('clinician', 'Clinician'), ('non_clinician', 'Non Clinician'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category'),
        ),
    ]
