# Generated by Django 6.0.1 on 2026-03-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='portfolio_url',
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_openings',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Openings'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='alternative_mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='Alternative Mobile Number'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='join_after',
            field=models.CharField(blank=True, max_length=100, verbose_name='Can join after'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='preferred_job_designation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preferred Job Designation'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='preferred_job_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preferred Job Location'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='total_experience',
            field=models.CharField(blank=True, max_length=100, verbose_name='Total Experience'),
        ),
    ]
