# Generated by Django 5.2.3 on 2026-01-31 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Requirement Template',
                'verbose_name_plural': 'Requirement Templates',
                'db_table': 'requirements_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequirementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500, verbose_name='Question')),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('email', 'Email')], default='text', max_length=20, verbose_name='Field Type')),
                ('field_name', models.CharField(help_text='Technical name for the field (snake_case)', max_length=100, verbose_name='Field Name')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('options', models.TextField(blank=True, help_text='For dropdown fields, comma-separated options', verbose_name='Options')),
                ('help_text', models.CharField(blank=True, help_text='Placeholder or helper text', max_length=255, verbose_name='Help Text')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='requirements.requirementtemplate')),
            ],
            options={
                'verbose_name': 'Requirement Field',
                'verbose_name_plural': 'Requirement Fields',
                'db_table': 'requirements_field',
                'ordering': ['template', 'display_order'],
            },
        ),
    ]
