# Generated by Django 5.2.3 on 2026-01-31 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('feedback_type', models.CharField(choices=[('general', 'General Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('praise', 'Praise')], default='general', max_length=20, verbose_name='Feedback Type')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True, verbose_name='Rating')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('page_url', models.URLField(blank=True, help_text='The page where the feedback was submitted', verbose_name='Page URL')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback/%Y/%m/', verbose_name='Attachment')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='new', max_length=20, verbose_name='Status')),
                ('admin_response', models.TextField(blank=True, verbose_name='Admin Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'feedback_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
