# Generated by Django 6.0.1 on 2026-03-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='Author Name')),
                ('author_position', models.CharField(help_text='e.g., CEO, Apple or Candidate', max_length=255, verbose_name='Position/Company')),
                ('content', models.TextField(verbose_name='Testimonial Content')),
                ('original_url', models.URLField(blank=True, help_text='Link to the original testimonial post', null=True, verbose_name='Original Post URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'feedback_testimonial',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
